spring:
  application:
    name: production
  profiles:
    default: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
